

CREATE TABLE STUDENTS (ID INTEGER PRIMARY KEY NOT NULL, FIRSTNAME TEXT NOT NULL, LASTNAME TEXT NOT NULL);

CREATE TABLE QUIZZES (ID INTEGER PRIMARY KEY NOT NULL, SUBJECT TEXT, NUM_QUESTIONS INTEGER, DATE_QUIZ TEXT);

CREATE TABLE RESULTS (STUDENT_ID INTEGER NOT NULL, QUIZ_ID INTEGER NOT NULL, SCORE INT);

INSERT INTO STUDENTS (ID, FIRSTNAME, LASTNAME) values (1, "John", "Smith");

INSERT INTO QUIZZES (ID, SUBJECT, NUM_QUESTIONS, DATE_QUIZ) values (1, "Python Basics", 5, "February 5th, 2015");

INSERT INTO RESULTS (STUDENT_ID, QUIZ_ID, SCORE) values (1,1,85);
